### PR TITLE
chore(plugins): which key plugin

### PR DESCRIPTION
**Pull request by rjshrjndrn**
It'll be helpful for newcomers to have some kind of keybinding helper

image

### CODE REVIEW

**Review by abuturaaab — CHANGES_REQUESTED** [review]
Please also update the `keymaps.lua` file, so after installation, it can be used right away.

**Comment by rjshrjndrn** [comment]
don't need that file, as we're not using a custom config file.

**Comment by Rishabh672003** [comment]
will can you make this PR on the https://github.com/LunarVim/nvim-basic-ide/tree/lazy branch i will merge this there

**Comment by rjshrjndrn** [comment]
I'm not using lazy yet. so once you merge lazy to main, I'll pull the changes to my fork, and update the PR

**Comment by Rishabh672003** [comment]
@rjshrjndrn just past this which-key config on that branch with the file in /user/whichkey i have added the plugin with lazy.nvim

**Comment by Rishabh672003** [comment]
added to the @lazy branch

**Comment by Rishabh672003** [comment]
this is now in the master

**Pull request closed without merging**
