### PR TITLE
updated the whole config (except dap) for neovim 0.8

### PR DESCRIPTION
**Pull request by Rishabh672003**
updated this whole config for neovim 0.8
also updated the readme accordingly
i dont know if this needs another branch or will merge in the main branch
also i updated the colorscheme to tokyonight  
only plugin that i havent updated are the dap ones because i dont use them and have no idea how to configure them

### CODE REVIEW

**Comment by Rishabh672003** [comment]
i have added so many configs lol, it will take chris weeks to review them lol

**Comment by Rishabh672003** [comment]
@ChristianChiarulli can you take look into this pr, and tell me if you want anything changed

**Comment by Rishabh672003** [comment]
there are somethings that i think have to be looked into 

- autocommands- i have added all the autocommands from my config i dont know which one should be removed
- autopairs - i have added a ts_config option, i guess its opinionated so i need to know should i remove it or not
- gitsigns - same as autopairs but in this one i copied my whole config, so remove the unnecessary lines

**Comment by cmndrsp0ck** [comment]
Pulled this down and it's working for me.

**Comment by Spaxly** [comment]
Same, it works great.

**Pull request merged**
