### PR TITLE
Neovim 0.9 release now with lazy.nvim many new things

### PR DESCRIPTION
**Pull request by Rishabh672003**

### CODE REVIEW

**Comment by jellydn** [comment]
FYI - I've migrated from Packer to Lazy for my nvim config. You could take a look for reference https://github.com/jellydn/nvim-ide

**Comment by Rishabh672003** [comment]
oh good to see someone has already done that with basic-ide
on a side note i did that for my configs https://github.com/rishabh672003/neovim some time ago now

**Comment by rrrix** [comment]
@Rishabh672003 you're changing a lot more than _just_ the plugin manager in this PR. 

You will have a far greater chance of getting this merged if you update your PR description with detail (justification) about what else you're changing (and why it should be in this PR). 

IMO if you want to perform other structural changes (file renames, variable/function refactoring) that should go into a seperate PR so they can be reviewed, critiqued, merged separately. 

Writing good PR's takes practice :) 

- https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/
- https://www.netlify.com/blog/2020/03/31/how-to-scope-down-prs/ 
- https://www.pullrequest.com/blog/writing-a-great-pull-request-description/

I wanted to give this a try, but after looking at the changes, it looks like there's too many other pieces being touched than just switching from `packer.nvim` to `lazy.nvim`.

**Comment by Rishabh672003** [comment]
> You will have a far greater chance of getting this merged if you update your PR description with detail (justification) about what else you're changing (and why it should be in this PR).

thanks for your worries and i do agree that this is not a perfect pr (and i am learning how to make one also these days i dont have a lot of time to work on this) 
But you dont need to worry about it because i am the one maintaining the repo and when this is completed i am the one that will merge it
Still thanks for your feedback

**Pull request merged**
