### PR TITLE
Update the plugin schema

### PR DESCRIPTION
**Pull request by MickTheRus**
Attempt to change the way plugins are being handled to more easily add/remove them.

### CODE REVIEW

**Comment by Rishabh672003** [comment]
autopairs arent working with this so this will have to wait to be merged @MickTheRus can you debug this please

**Comment by MickTheRus** [comment]
> autopairs arent working with this so this will have to wait to be merged @MickTheRus can you debug this please

A bit busy yesterday and today with Easter,  one I get free time I'll get on it.

**Comment by Rishabh672003** [comment]
no worries was planning to merge this today, well now will see next week

**Comment by MickTheRus** [comment]
@Rishabh672003 I figured out what the issue of autopairs was. Is there a reason you removed the section about disabling built in rtp plugins?

**Comment by Rishabh672003** [comment]
> 

they were just all commented so i removed them just because

**Review by Rishabh672003 — APPROVED** [review]
> becase Lua > Vim Script

100%

**Comment by Rishabh672003** [comment]
Now this looks good to me still i will check it for more couple of days and will merge it when i got time

**Comment by MickTheRus** [comment]
> > 
> 
> they were just all commented so i removed them just because
> 

I did that for people to set their own what they need/ don't need

**Comment by Rishabh672003** [comment]
discovered another bug - the arrow keys arent working in telescope i see you have set them in the config but that isnt working
It can be another bug of Lazy's opt @MickTheRus

**Comment by MickTheRus** [comment]
In class ATM, will fix it later

**Comment by Rishabh672003** [comment]
no worries dude, you can do it whenever you have time

**Comment by Rishabh672003** [comment]
Hey i fixed it myself, you mapped to the wrong thing

**Comment by Rishabh672003** [comment]
> I did that for people to set their own what they need/ don't need

Yeah i guess we could leave it there then

**Comment by Rishabh672003** [comment]
> So we good to merge?

Mostly yes but i will still test it for a day or two to make sure there are no things that i missed.

Also you know this pr really changes the previous structure we had, so i think we should also work on the readme and actually explain how we are doing things here and how can user expand it, but i guys that can be a separate pr after we merge this, wt do you think?

**Pull request merged**
