### PR TITLE
Show error messages

### PR DESCRIPTION
**Pull request by MahanRahmati**
- Add nvim-notify
- Fix some formatting issues

### CODE REVIEW

**Comment by MahanRahmati** [comment]
@ChristianChiarulli 
I can remove nvim-notify and use vim.api.nvim_err_writeln instead.
Should I do it?

**Comment by tonycurcuru7** [comment]
Nope!

**Comment by Rishabh672003** [comment]
i think i know what chris will say - this just adds more noise and not needed for a basic ide

**Comment by Rishabh672003** [comment]
we will not add more plugins which are not necessary

**Pull request closed without merging**
