### PR TITLE
Fix LSP complaining about deprecation

### PR DESCRIPTION
**Pull request by Spaxly**
This is to fix LSP complaining about a deprecation

### CODE REVIEW

**Comment by Rishabh672003** [comment]
chris merge this, this solves the issue of lsp error

**Comment by raman08** [comment]
@ChristianChiarulli you can merge this

**Comment by ChristianChiarulli** [comment]
pls fix conflicts

**Comment by Rishabh672003** [comment]
hey @Spaxly make a new pr from the master this one is old has conflicts

**Comment by Spaxly** [comment]
> hey @Spaxly make a new pr from the master this one is old has conflicts

aight will do.

**Pull request closed without merging**
